08-Apr-20 19:47:25 - 17
08-Apr-20 19:47:25 - Can't create directory /home/fisher/tests/www-python-org_files
08-Apr-20 20:25:19 - Traceback (most recent call last):
  File "/home/fisher/python-project-lvl3/page_loader/page_loader.py", line 33, in page_loader
    os.mkdir(full_dir_name)
FileExistsError: [Errno 17] File exists: '/home/fisher/tests/www-python-org_files'

08-Apr-20 20:25:19 - Can't create directory /home/fisher/tests/www-python-org_files
08-Apr-20 20:52:17 - Traceback (most recent call last):
  File "/home/fisher/python-project-lvl3/page_loader/page_loader.py", line 33, in page_loader
    os.mkdir(full_dir_name)
FileExistsError: [Errno 17] File exists: '/home/fisher/tests/www-python-org_files'

08-Apr-20 20:52:17 - Can't create directory /home/fisher/tests/www-python-org_files
08-Apr-20 21:03:04 - Invalid URL 'www.tim.org/thesinger.html': No schema supplied. Perhaps you meant http://www.tim.org/thesinger.html?
08-Apr-20 21:04:05 - Traceback (most recent call last):
  File "/home/fisher/python-project-lvl3/page_loader/page_loader.py", line 34, in page_loader
    os.mkdir(full_dir_name)
FileExistsError: [Errno 17] File exists: '/home/fisher/tests/www-tim-org-thesinger-html_files'

08-Apr-20 21:04:05 - Can't create directory /home/fisher/tests/www-tim-org-thesinger-html_files
08-Apr-20 21:04:48 - Starting new HTTP connection (1): www.tim.org:80
08-Apr-20 21:04:50 - http://www.tim.org:80 "GET /thesinger.html HTTP/1.1" 200 854
08-Apr-20 21:04:50 - Save http://www.tim.org/thesinger.html
as /home/fisher/tests/www-tim-org-thesinger-html.html
